# carddataclass.py

'''Card data class with class attributes, data attributes,
    autogenerated methods and explicitly defined methods.'''

from dataclasses import dataclass
from typing import ClassVar, List

@dataclass
class Card:
    